### ISSUE TITLE
Define the Dreamcatcher

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#1]
Define in whitepaper form, using [this md file as a start point](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/docs/wp_dreamcatcher.md).  

Goal
What is the goal of dreamcatcher

What, who and why
What does dream catcher do, who does it do it for and why do they want to do that?

Alternatives
What is the best current and foreseeable future alternative for each need identified in 1 and what makes dc better than that alternative

Red queen
What is the sustainable competitive advantage that allows dc to stay ahead ahead of the alternatives

Components
What are the components of the system. How do they work and how do they interact

(copied from dreamcatcher-tech/dev.to#2)

**Comment by evil-liskov** [comment]
These questions have been answered in the [dreamcatcher doc](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/docs/wp_dreamcatcher.md) as well as for some dependent projects, such as interblock.

The website has been published on https://dreamcatcher-tech.github.io/
