### ISSUE TITLE
Correct "Bid Attribution split" field in NFAs

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#11]
For example, in [003 Company Structure.md](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/nfas/NFAs/Operations/003%20Company%20Structure.md#bid-attribution-split) the `Bid Attribution split` field lists what other NFAs are due attribution - this field is supposed to be used as a negotiation tool with the person offering to do the work, not as a dependency graph, which is how it is being used now.

A good way to fix this more permanently is to define what each field means in the template.

**Comment by TemperBead** [comment]
Agreed - it's ambiguous.  I'll change the guidance line for the fields.  We already have Dependencies so presumably that serves.

So
- Bid Attribution Split:  Current (negotiated) Attribution for the NFA that is being produced.
- Dependencies: Other upstream NFAs which this NFA requires.
