### ISSUE TITLE
01 Dreamcatcher.md does not mention NFTs

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#21]
There is nothing in this document that mentions the recording of Requests in NFT form, and no mention of Ideas being part of a marketplace.  The tactical intent is worded purely in execution mode, after all the discovery and negotiation of _what_ needs to be done has already occured.

**Comment by TemperBead** [comment]
Yea, this doc was concurrent or prior to quite a few conversations, so have spent most of today updating [01 Dreamcatcher](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/nfas/Requests/01%20Dreamcatcher.md).

Have done so with the aim of maintaining it as a pure problem statement.  So have attempted to avoid stepping into the Idea that we already have in mind - quite tricky bear in mind but a good discipline.  

One interesting axiom from this exercise - Requests should use as close to generally accepted natural language as possible, and avoid definitions.  Requests don't need to be exact, they need to be evocative.  They can't be directly contracted against so there's no issue with people being shafted if they read it slightly differently, but by aiming to only use generally accepted language we're getting the gist of what's needed over, and leaving it more open to the real negotiation stage which is the Idea.

Interestingly, by doing that today it did point to another missing component under existing tech.  It's a pre-existing solution, but is that an Idea?  Ideas are yet-to-exist tech.  Helped sharpen that a bit.

Open to comments on this one.  I think it a good guideline that we should follow, and encourage others to as well.

Upshot is, I've tried to avoid the specific terms in favour of more general terms, and have tried to avoid solutioneering.

So in this update, broadly, Requests=problems, Ideas=solutions, NFTs=proof of ownership.

Another area that we developed after this v0.1 of this doc was pools.  I've put in wording to allow for that but will probably need to go back tomorrow to that.

**Comment by inverted-capital** [comment]
From what you're saying in your comment, what are proposing be changed in what documents ?

**Comment by TemperBead** [comment]
Have already updated [01 Dreamcatcher](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/nfas/Requests/01%20Dreamcatcher.md) with [this commit](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/commit/95bbfdfd4b4f52ae921eb4a44e9595846c340f70).  Need to add in more to deal with pools, but thinking maybe pools should be a nested Request?
