### ISSUE TITLE
06 Interblock.md does not mention privacy

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#22]

**Comment by TemperBead** [comment]
Added points 12-14 in [Interblock.md](../blob/master/website/nfas/Requests/06%20Interblock.md)

Have mirrored the [Privacy stance of IPFS](https://docs.ipfs.io/concepts/privacy-and-encryption/#what-s-public-on-ipfs), with the addition of private groups.  Let me know if this covers everything.
