### ISSUE TITLE
Future work stack rank has no cohesion

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#24]
What is the top level purpose guiding the work on all of these things ?

Why are so many Requests and Ideas being lodged ?

Surely a Request / Idea pair can be created that describes the work you plan to do amongst these numerous items in the stack ?

**Comment by TemperBead** [comment]
Fair point.  Will put in some stub-ish Requests today.

**Comment by TemperBead** [comment]
See [10 Request-Idea](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/nfas/Requests/10%20Request-Idea.md)

**Comment by TemperBead** [comment]
On an additional point that I think we need to make explicit - Ideas can embed Requests.  

So e.g. 

Request: I need to get over this river
Idea: Use a boat.  I have a boat.  I don't have fuel.  Request: I need fuel.

**Comment by inverted-capital** [comment]
as per #31 yes on the nesting.  R10 Request-Idea is good.  Lets get that past QA and into the pool.  Happy to close this.
