### ISSUE TITLE
Unsure how to do `typeof` references

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#3]
eg: for "Pull Request Contract" this is a `typeof` Contract - we need a way to capture this relationship in the docs somehow.

**Comment by TemperBead** [comment]
Perhaps:

Pull Request Contract: typeof [Contract](https://dreamcatcher-tech.github.io/docs/User_Dictionary/Contract)

**Comment by inverted-capital** [comment]
@TemperBead can we close this ?  This issue is covered by using a folder to describe typeof, corret ?

**Comment by TemperBead** [comment]
Correct.  Folder names are used to denote typeof for the definitions within that folder.
