### ISSUE TITLE
The naive numbering for Requests and Ideas are already clashing

### ISSUE THREAD

**Issue by TemperBead** [dreamcatcher-tech/dreamcatcher-tech.github.io#30]
We need to think of a more robust way to number Requests and Ideas.

E.g. While writing Requests I created request 07.  07 was not in use as a Request, but was in use as an Idea.

The numbering system needs to take into account that it may be Ideas that come first or Requests.

This will be solved when we get unique chain IDs, but in the mean time it isn't solved.

Suggest renaming along the lines of:  R07, I07 to remove the clash.  However, that still leaves the assumed link between both 07s.

Not going to do any renaming right now, but let me know if the above bodge is ok for now.

**Comment by inverted-capital** [comment]
Absolutely lets rename as you suggest.  The numbers for Requests are separate from those for Ideas.  There is no link between `R07` and `I07` and we are the only users of the markdown based system for now.

**Comment by inverted-capital** [comment]
If we get to R99 and we still don't have a software version, we will have a different kind of problem....
