### ISSUE TITLE
Are the proposal scope documents misplaced ?

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#32]
Why has [this document](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/78e38d15b4476942bd59bd406e0ec63d8c0c543f/website/nfas/Ideas/02%20Funding.md) been created ?

Was it to reserve a matching ID is the Ideas section ?

If so, that misses the point of separating Requests and Ideas - the IDs are independent because one Request can have many Ideas targeted at it, and one Idea can satisfy many Requests.

**Comment by TemperBead** [comment]
On listening through our recording from this morning - continue to agree with the use of IDs for docs and not linking them in a hierarchy.  Think this is a graph of relationships.  

Somewhat concerned that we're going to end up hunting and pecking around for the docs we need and need to reference - would be lovely to have an actual graph of the pool space, but in the mean time once you've done the renaming I'm going to make an index of those relationships between docs in an md file.  

This is just admin, but feel free to use and might point to something that'll be useful down the road.

**Comment by inverted-capital** [comment]
So we can close this issue then ?

**Comment by TemperBead** [comment]
Yup, all good.
