### ISSUE TITLE
Two levels of Pool QA

### ISSUE THREAD

**Issue by TemperBead** [dreamcatcher-tech/dreamcatcher-tech.github.io#35]
If the objective is to get a Pool to fund the creation of an asset, we have two stages to consider:

1. Passing the QA step for the Request/Idea format, based on the QA requirements the pool has defined.
2. Convincing the Pool (or for the Pool to convince itself) that this is a good thing to put money into escrow for.

The first is obvious enough - analogous to an application form.  If you haven't provided the right level of info in the right way, go back and do it again.

The second isn't as obvious when it gets to multiple options.  Say e.g. the Pool wants to consider putting escrow into Idea_B.   In order to work, Ideas C, D or E are required.  Should the pool put escrow into Req_B and QA release it to the first of those Ideas to deliver?  Or should a pool only put escrow up against a leaf of the tree, and so make a choice between C, D or E?  Or should it batch up the escrow, e.g. if they want Req A to happen, is escrow against (Req A, Idea A), (Req A, Idea B) - in which case Req B might not be funded.

So where there's multiple options to bring together Req/Ideas to produce a bracket, a Pool may prefer or only have cash to fund one trace through the graph and not another.  Same applies to a qualitative decision if there's a duff idea in there they want to avoid.

These are the options that I can see:
1. Pools only consider escrowing a Requests/Ideas without any Dependencies.  
2. Pools consider the graph, and escrows specific Requests/Ideas in either individually, but with a common goal in mind
3. Pools create rules for use of escrow that include some logic between Requests/Ideas.  E.g. We want ReqA to happen.  if Idea_A delivers before Idea B, we're not going to pay out on Idea C.

```mermaid
  graph TD;
      Idea_A-- Targets -->Req_A;
      Idea_B--Targets -->Req_A;
      Idea_B--Dependency-->Req_B;
      Idea_C--Targets -->Req_B;
      Idea_D--Targets -->Req_B;
      Idea_E--Targets -->Req_B;
```

**Comment by TemperBead** [comment]
Closing this as resolved.  The decision is that we're going to use a first-past-the-post claim for escrow, and that we don't need to address multiple nesting of overlapping Ideas for now.

**Comment by inverted-capital** [comment]
So we can close this based on our discussion that the correct place to place graph restrictions is on each node, rather than the graph as a whole, correct ?
