### ISSUE TITLE
Escrowing Process

### ISSUE THREAD

**Issue by TemperBead** [dreamcatcher-tech/dreamcatcher-tech.github.io#38]
At its simplest, no one escrows cash in advance, everyone builds forward apps.

Cash can also be escrowed unconditionally against an Idea.  I.e. the funder thinks the Idea hits everything, so here's an escrow to encourage someone to do it.

However, can you also apply requests for alterations to an Idea against your escrowed cash?  Ie if Idea A is almost right, and would be perfect if just a few changes were made, could a Funder offer up Escrow with those changes as requirements to call down the escrowed cash?  Presumably if you can then it's a short step to negotiation.  E.g. I escrow against an idea, and offer to contract for the changes I think I want.  A worker then discusses those changes and comes to an agreement, at which point the escrow is put in place.

**Comment by inverted-capital** [comment]
I don't understand the first 2 lines ?

If you want something close to something else, then just fork the Idea, and fund that ? 
Or make a new request that says "just like this Idea, but different in these ways ..." ?
