### ISSUE TITLE
Fractional work/funding

### ISSUE THREAD

**Issue by TemperBead** [dreamcatcher-tech/dreamcatcher-tech.github.io#43]
We don't need to answer this now, but getting it down to work on later.

in the current [I11 Request-Idea](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/nfas/Ideas/I11.md) process, which is as simple as we can get (IMO) we have:

```mermaid

stateDiagram
    direction LR

    
    [*] --> Dust
    Dust --> poolEntryQA : submit
    poolEntryQA --> Dust : fail
    poolEntryQA --> inPool : pass
    state inPool {
      direction LR
    [*] --> Open
      inCompletionQA --> Locked : fail
      Locked --> inCompletionQA : submit
      Open --> Locked : Funding / Work
      Locked --> Locked : Funding / Work
    inCompletionQA --> Finalised : Pass
    }
    
```
In the situation of a single funder and a single worker, this works.  It becomes less clear what the trigger point is for, say, a crowd-funded piece of work, or an unfunded piece of work.

E.g. If I write a Request/Idea and have that accepted into the Pool, it's now available for funding based on the pools governance.  That's cool.  But to move to "Locked" i.e, work in progress, in that it has some funding and some worker effort being applied and isn't on the shelf, what would be the trigger point?  If something that was in "open" had $5 put to it, would that make it Locked?  

I reckon it should, but does serve to weaken the need for Locked as a state, as there's only a gradual change involving the addition of worker effort and funder capital, rather than a state change triggered on an event as in the diagram above.

As mentioned above, not for now and more of a note to self, as in the simple case they state chart above works.

**Comment by inverted-capital** [comment]
Locked is a process of negotiation between workers and funders.  Upon reaching lock, some funders have agreed to pay some money when some workers complete the job.

I think the error in this question is that the Open to Locked transition isn't just whenever any funding or work gets added, but rather when an agreement has been reached.  In our paper version we don't have any hope of doing multiple locks, but I don't see any problem with allowing any number of locks to be in progress simultaneously as well as extra conditions such as locked for any worker at all, locked for some specific workers, locked for anyone but this particular worker I dislike, etc.

A better question is how to handle some locked work being completed by a totally different group of workers using some of the partial work of the locked workers ?

Great statechart btw.

**Comment by inverted-capital** [comment]
Would closing this ticket be writing this process up in our process description somewhere ?  That statechart definitely belongs somewhere solid, as an output.

**Comment by TemperBead** [comment]
On your point re:  Locked is a process of negotiation between workers and funders, and the subsequent point on multiple locks:

I agree with what you say on both.  Will point to a couple of repercussions though (which we don't need to deal with for this minimal version but want to record while they're fresh):

1.  A Request/Idea in Open can still be worked on without that contract lock.  As in, if a Request/Idea is in Open, and permissionless work is done, that should be recorded as a contribution. 
2. A Request/Idea can be worked on by both contracted and permissionless workers.  So the state change from Open->Locked could actually be quite far down the road say if it's been half completed during Open.
3.  Funding during Open should also be allowed and is similar to crowdfunding in many ways - it isn't a contract, it's chucking $5 in as encouragement say.  May be that this is too securities-like though.

But yes, I'll edit [I11](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/3b49943a14d6843c9d6ad04a4c8039e97791ce78/website/nfas/Ideas/I11.md) definition of Locked.

On how to handle partial work being completed by workers where that work is locked, I don't see a major problem with that bearing in mind that a worker can also be a funder.  So if this was done with permission, it would be a sub-contract.  If it was done without permission, then it's permissionless work that would be noted as a contribution, with the impact decided by the attribution algo.

Would add though that the negotiation, contract, escrow, release cycle will probably need a separate Request/Idea as there's hidden complexities there that we don't need to solve yet, but will need to soon.
