### ISSUE TITLE
I11 ideas in dust mode should not be listed in market, nor should they be in drafts

### ISSUE THREAD

**Issue by panick-carousel** [dreamcatcher-tech/dreamcatcher-tech.github.io#48]
I have not been using the drafts folder in NFAs as I think the whole folder is now drafts.

We should not record these items in market.md as the pool should be largely unaware of the dust.

**Comment by TemperBead** [comment]
Yes, that works.

So:

Dust -> [website/nfas](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/tree/master/website/nfas)
Open -> [website/pool](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/tree/master/website/pool)

We don't need a separate folder for Locked or Finalised as there's no fork involved, only a state change that's noted in market.md.  Outputs are wherever they are, but linked from market.md.

And we get rid of website/nfas/drafts.

Agree?  Easy change to make so will just go ahead and can always revert.

**Comment by TemperBead** [comment]
I've just moved the [Request Template](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/pool/Request%20Template.md) and [Idea Template](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/pool/Idea%20Template.md) out of nfa/drafts as agree drafts don't make sense and not being used, so we should get rid.

That location I've moved them to may not be where they end up eventually.  They're Outputs and available for others to use and riff on, but as Outputs aren't linked to any particular pool folder structure, have put them there for now as need to reference them from [Pool Process.md](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/new/master/website/pool) and am bootstrapping somewhat...

Not high priority, but we should move [Immutable Permissioning.md](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/master/website/nfas/Drafts/Immutable%20Permissioning.md) and the contents of [Provenance Accounting](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/tree/master/website/nfas/Drafts/Provenance%20Accounting) into nfa/Requests.
