### ISSUE TITLE
I11 too many actors - there should only be funders, workers, and QA

### ISSUE THREAD

**Issue by panick-carousel** [dreamcatcher-tech/dreamcatcher-tech.github.io#49]
I do not see the benefit from the extra distinctions, especially given the limited scope of I11 where it is paper based only.

**Comment by TemperBead** [comment]
It's because of the various hats thing and is dictated by the process.  However... 

I can reduce the number of actors by moving actions that can be carried out under the main types without losing fidelity.  Will do that.

**Comment by TemperBead** [comment]
OK, done.  I've reduced it to QA, Workers, Funders and Moderator.  I propose we keep Moderator in there as that was the only role I couldn't reduce into another, as that has to do with the functioning of the Pool not the use of the Pool.  

Let me know if you're ok with that and feel free to close this issue if you are, or comment further.

**Comment by panick-carousel** [comment]
Ok yes to moderator - we're on the same page with that actor.
